-- тестовый раздел
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme1', 'testText',current_timestamp,'5');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme2', 'testText',current_timestamp,'5');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme3', 'testText',current_timestamp,'57');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme4', 'testText',current_timestamp,'56');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme5', 'testText',current_timestamp,'55');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme6', 'testText',current_timestamp,'54');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme7', 'testText',current_timestamp,'53');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme8', 'testText',current_timestamp,'52');
INSERT INTO themes (section_name, user_id, theme, text, published, score) VALUES ((select name from sections where name = 'TestSection1'),(select id from users where sign = 'TestSignature'),'TestTheme9', 'testText',current_timestamp,'51');